title: Project Physica
lang: en
description: Project Physica is a company that makes lots of projects based of physics principles like quantum and atomic mechanics.

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
